# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_ARCH_PENTAGRAM) += clk-sunplus.o

# SoC Drivers
obj-$(CONFIG_TARGET_PENTAGRAM_COMMON) += clk-q628.o
obj-$(CONFIG_TARGET_PENTAGRAM_Q645) += clk-q645.o
obj-$(CONFIG_TARGET_PENTAGRAM_SP7350) += clk-sp7350.o
