#
# (C) Copyright 2012 The Chromium Authors
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += hw/sc_spacc.o hw/host_hpi.o

obj-y += sw/libeddsa/lib/burn.o \
	sw/libeddsa/lib/burnstack.o \
	sw/libeddsa/lib/ed25519-sha512.o \
	sw/libeddsa/lib/ed.o \
	sw/libeddsa/lib/fld.o \
	sw/libeddsa/lib/sc.o \
	sw/libeddsa/lib/x25519.o \
	sw/linux/crypto/sha3_generic.o \
	sw/wpa_supplicant/src/crypto/aes-gcm.o

obj-y += sc_api.o
obj-y += secure_verify.o


