# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2022 Sunplus - All Rights Reserved
# Hammer Hsieh, Sunplus Software Engineering, hammer.hsieh@sunplus.com

obj-$(CONFIG_VIDEO_SP7350) += sp7350_display.o disp_tcon.o disp_dmix.o disp_tgen.o disp_vpp.o disp_osd.o disp_mipitx.o