obj-$(CONFIG_PINCTRL_SUNPLUS) += pinctrl_sunplus.o pinctrl_gpio_exp.o sp7021_group.o
obj-$(CONFIG_PINCTRL_SUNPLUS_Q645) += pinctrl_sunplus.o pinctrl_gpio_exp.o q645_group.o
obj-$(CONFIG_PINCTRL_SUNPLUS_SP7350) += pinctrl_sunplus.o pinctrl_gpio_exp.o sp7350_group.o
