/* ==========================================================================
* Synopsys DesignWare Secure Subsystem Software Driver and
* documentation (hereinafter, "Software") is an Unsupported proprietary work
* of Synopsys, Inc. unless otherwise expressly agreed to in writing between
* Synopsys and you.
*
* The Software IS NOT an item of Licensed Software or Licensed Product under
* any End User Software License Agreement or Agreement for Licensed Product
* with Synopsys or any supplement thereto. You are permitted to use and
* redistribute this Software in source and binary forms, with or without
* modification, provided that redistributions of source code must retain this
* notice. You may not view, use, disclose, copy or distribute this file or
* any information contained herein except pursuant to this license grant from
* Synopsys. If you do not agree with this notice, including the disclaimer
* below, then you are not authorized to use the Software.
*
* THIS SOFTWARE IS BEING DISTRIBUTED BY SYNOPSYS SOLELY ON AN "AS IS" BASIS
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE HEREBY DISCLAIMED. IN NO EVENT SHALL SYNOPSYS BE LIABLE FOR ANY DIRECT,
* INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
* SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
* CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
* ========================================================================== */
/*==========================================================================
* Build ID: 2.0.0
* ========================================================================== */

/* **** DO NOT EDIT - this file is generated by ARChitect **** */

#ifndef _DSS_CONFIG_H_
#define _DSS_CONFIG_H_


#define DSS_TIMER0_PRESENT
#define DSS_TIMER1_PRESENT
#define DSS_AHB_ML_PRESENT
#define DSS_AHB_ML_REG_BASE (0xE0001000)
#define DSS_AHB_ML_LOW_REGIONS_CAN_ACCESS_SYS_MST  (true)
#define DSS_SYSMST_REG_BASE (0xE0007000)
#define DSS_SYSMST_PRESENT
#define DSS_SYSMST_REMAP_PRESENT
#define DSS_SYSMST_REMAP_CLUSTER  (1)
#define DSS_SYSSLV_PRESENT
#define DSS_SYSSLV_REG_BASE (0xE0006000)
#define DSS_SYSSLV_RANGE_CNT  (3)
#define DSS_EDU_PRESENT
#define DSS_EDU_REG_BASE (0xE0020000)
#define DSS_EDU_TTT_SIZE  (10)
#define DSS_EDU_TTT_IS_PROGRAMMABLE
#define DSS_RTC_PRESENT
#define DSS_RTC_REG_BASE (0xE0004000)
#define DSS_SKS0_PRESENT
#define DSS_SKS0_REG_BASE  (0xE0002000)
#define DSS_SKS0_NUM_SLOTS (8)
#define DSS_SKS0_MAX_WDS   (16)
#define DSS_SKS0_NUM_CTX   (16)
#define DSS_CRU_PRESENT
#define DSS_CRU_REG_BASE (0xE7FF0000) 

#define DSS_DMAC_CHAN_CNT     (1)
#define DSS_DMAC_MEM_CHAN_CNT (1)
#define DSS_DMAC_AUX_CHAN_CNT (0)
#define DSS_DMAC_SW_CHAN      (0)
#define DSS_UART0_PRESENT
#define DSS_UART0_REG_BASE (0xE0024000)
#define DSS_UART0_FS (32)
#define DSS_HPI_PRESENT
#define DSS_HPI_REG_BASE (0xE7FF1000) 

#define DSS_MPU_PRESENT
#define DSS_MPU_MIN_REGION (false)
#define DSS_MPU_REGION_CNT (8)
#define DSS_WATCHDOG_PRESENT
#define DSS_WATCHDOG_SIZE    (32)
#define DSS_DID_PRESENT
#define DSS_PKA_PRESENT
#define DSS_PKA_REG_BASE (0xE7FF8000)
#define DSS_PKA_RSA_OP_SIZE	(4096)
#define DSS_PKA_ECC_OP_SIZE	(1024)
#define DSS_PKA_ALU_BIT_WIDTH	(128)
#define DSS_AIC_PRESENT
#define DSS_AIC_REG_BASE        (0xE0000400)
#define DSS_AIC_CACHE_LINE_LEN  (64)
#define DSS_AIC_NUM_CACHE_LINES (16)
#define DSS_AIC_MAC_LEN         (16)
#define DSS_AIC_IVC_CACHE_LINE  (16)
#define DSS_ADC_PRESENT
#define DSS_ADC_REG_BASE        (0xE0000800)
#define DSS_ADC_CACHE_LINE_LEN  (64)
#define DSS_ADC_NUM_CACHE_LINES (16)
#define DSS_ADC_MAC_LEN         (16)
#define DSS_ADC_MEM_BASE        (0xD0000000) 

#endif
